[Service]
# Fix runtime dir ownership to avoid "Failed to open PID file: Permission denied"
ExecStartPre=/bin/mkdir -p /run/nvidia-persistenced
ExecStartPre=/bin/chown nvidia-persistenced:nvidia-persistenced /run/nvidia-persistenced
ExecStartPre=/bin/rm -f /run/nvidia-persistenced/nvidia-persistenced.pid

# Override ExecStart from the packaged unit
ExecStart=
ExecStart=/usr/bin/nvidia-persistenced --user nvidia-persistenced --uvm-persistence-mode --verbose

# Set ReadyState after daemon is up
ExecStartPost=-/usr/bin/nvidia-smi conf-compute -srs 1
